services:
  - type: web
    name: result-website
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Result_website.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Result_website.settings
      - key: PYTHON_VERSION
        value: 3.11
    autoDeploy: true
