services:
  - type: web
    name: Result_website
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ResultWebsite.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ResultWebsite.settings
      - key: PYTHON_VERSION
        value: 3.11
    autoDeploy: true
